# Generated by Django 4.1.3 on 2022-11-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll_no", models.IntegerField()),
                ("mark1", models.IntegerField()),
                ("mark2", models.IntegerField()),
                ("mark3", models.IntegerField()),
                ("passed", models.BooleanField()),
            ],
        ),
    ]
